<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yottaverse.MachineOps.Application\Yottaverse.MachineOps.Application.csproj" />
    <ProjectReference Include="..\Yottaverse.MachineOps.Core\Yottaverse.MachineOps.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Yottaverse.MachineOps.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Database\Migrations\*.sql" />
  </ItemGroup>

</Project>
